global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'consul-spring-boot'
    metrics_path: '/actuator/prometheus'
    consul_sd_configs:
      - server: 'consul:8500'
        services: []       
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,springboot,.*
        action: keep

      - source_labels: [__meta_consul_service]
        target_label: job

      - source_labels: [__meta_consul_dc]
        regex:         '(.*)'
        target_label:  dc
        replacement:   ${1}        
